### ISSUE TITLE
esrv_youtube crashes WACUP

### ISSUE THREAD

**Issue by r4dian** [luthor112/WinampEasyService#1] opened 2023-09-27 11:00 UTC
Pre-Requisites: 
1. Install Preview Version: 1.9.19.16956 (x86) from https://getwacup.com/preview/
2. Download the WinampEasyService 2023-09-23 Release Binaries 
3. Put the ml_easysrv and in_easyfngetter plugins in the WACUP Plugins folder
4. Also put isrv_managed in the WACUP Plugins folder
5. Copy the content of WinampEasyServicePlugins to the Plugins folder

Steps:
1. Open WACUP & the Media Lib (Alt-L)
2. In the services tab go to YouTube
3. Click Invoke Plugin & enter a search term
4. After some time, or on the next click WACUP will crash

System:
-  Windows 11 Pro build 22621.2215
- dotnet 6.0.22

**Comment by luthor112** [comment] 2023-09-28 15:49
Hi!
Try setting this...:
WACUP Preferences -> Playlist -> Titles|ATF -> Metadata Reading
...to this...:
Read metadata only when fie(s) are played
... and try again.

**Comment by luthor112** [comment] 2023-09-28 15:50
Unfortunately, srv_youtube is the most unstable of the plugins.

**Comment by luthor112** [comment] 2024-04-03 13:41
Does this still happen?

**Comment by r4dian** [comment] 2024-04-06 14:10
I don't have the same PC anymore, so I tried with a fresh install ( and WACUP Preview v1.9.20.17040 ) and these plugins don't load at all.

**Comment by luthor112** [comment] 2024-04-15 21:31
Duplicate of #2

**Closed as completed by luthor112** 2024-04-15 21:31 UTC
